<?php

/**
 * RF-31: the documentation tree matches the code this feature shipped.
 *
 * Two ownership regimes are asserted, because mixing them is how the tree
 * rots: `docs/agents/*.md` are machine-generated by `/ai-context` and carry
 * the generation banner, while `CLAUDE.md` and `AGENTS.md` are hand-written,
 * carry no banner and are never machine-overwritten. No `AI_CONTEXT.md`
 * exists — the canonical tree is `AGENTS.md` + `docs/agents/*.md`.
 */

/**
 * The eight machine-generated context files, as repo-relative paths.
 *
 * @return list<string>
 */
function generatedContextDocuments(): array
{
    return [
        'docs/agents/api_contracts.md',
        'docs/agents/architecture.md',
        'docs/agents/coding_guidelines.md',
        'docs/agents/data_model.md',
        'docs/agents/dependencies.md',
        'docs/agents/domain_rules.md',
        'docs/agents/project_overview.md',
        'docs/agents/tech_stack.md',
    ];
}

/**
 * The "Limites conhecidos" table of the onboarding guide, as raw markdown.
 */
function onboardingKnownLimitsSection(): string
{
    $contents = file_get_contents(base_path('docs/onboarding-albuquerque.md'));
    $start = strpos($contents, '### Limites conhecidos');

    expect($start)->not->toBeFalse('A seção "Limites conhecidos" sumiu do onboarding.');

    return substr($contents, $start);
}

test('no AI_CONTEXT.md exists anywhere in the tree (ADENDO D-2)', function () {
    $found = [];

    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator(base_path(), FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST,
    );

    foreach ($iterator as $file) {
        $path = str_replace('\\', '/', $file->getPathname());

        if (str_contains($path, '/vendor/') || str_contains($path, '/node_modules/')) {
            continue;
        }

        if ($file->isFile() && $file->getFilename() === 'AI_CONTEXT.md') {
            $found[] = str_replace(base_path().'/', '', $path);
        }
    }

    expect($found)->toBe([], 'A árvore canônica é AGENTS.md + docs/agents/*.md; nenhum AI_CONTEXT.md deve existir.');
});

test('every docs/agents file carries the generation banner', function (string $relativePath) {
    expect(base_path($relativePath))->toBeReadableFile();

    $lines = file(base_path($relativePath), FILE_IGNORE_NEW_LINES);

    expect($lines[2] ?? '')->toBe('<!-- Generated by /ai-context. Manual edits are overwritten on re-run. -->');
})->with(generatedContextDocuments());

test('the hand-written context files carry no ownership banner (they are never machine-overwritten)', function (string $relativePath) {
    $lines = file(base_path($relativePath), FILE_IGNORE_NEW_LINES);

    expect($lines[2] ?? '')->not->toStartWith('<!-- Generated by /ai-context.');
})->with(['CLAUDE.md', 'AGENTS.md']);

test('the regenerated api_contracts records the Visão Geral route and the new query string contract', function () {
    $contents = file_get_contents(base_path('docs/agents/api_contracts.md'));

    expect($contents)
        ->toContain('/suprimentos/visao-geral')
        ->toContain('suprimentos.visao-geral')
        ->toContain('VisaoGeral');

    foreach (['search', 'obraId', 'statusId', 'priorityId', 'responsibleId', 'neededAtFrom', 'neededAtTo', 'requestedFrom', 'requestedTo', 'atrasado', 'pendente', 'entregue'] as $parameter) {
        expect($contents)->toContain($parameter);
    }
});

test('the regenerated tree records the 8-key compute shape and the RNF-10 debt', function () {
    $tree = implode("\n", array_map(
        fn (string $relativePath): string => file_get_contents(base_path($relativePath)),
        generatedContextDocuments(),
    ));

    expect($tree)
        ->toContain('entregues')
        ->toContain('entreguesHoje')
        ->toContain('5 000')
        ->toContain('users_email_lower_unique')
        ->toContain('EmailNormalizer')
        ->toContain('#[Url]');
});

test('CLAUDE.md records the decisions this feature settled (RF-31)', function (string $needle) {
    expect(file_get_contents(base_path('CLAUDE.md')))->toContain($needle);
})->with([
    'inline svg charts' => 'Gráficos em SVG inline, sem biblioteca de chart',
    'visibleTo first' => '`visibleTo` antes de qualquer filtro',
    'url attribute convention' => '`#[Url]` é o único mecanismo de estado de filtro',
    'canonical email rule' => 'EmailNormalizer::normalize',
    'functional unique index' => 'users_email_lower_unique',
    'entregues hoje key' => 'entreguesHoje',
    'demo seeder caveat' => 'Ressalva operacional do `DemoSeeder`',
    'visao geral route' => 'suprimentos.visao-geral',
    'no AI_CONTEXT' => 'Não existe `AI_CONTEXT.md` neste repositório',
]);

test('CLAUDE.md no longer lists the divergences this feature closed (RF-31)', function () {
    $contents = file_get_contents(base_path('CLAUDE.md'));

    expect($contents)
        ->not->toContain('listagens só têm busca textual, atraso e datas')
        ->not->toContain('PRD §26 dashboard de Suprimentos → não implementado')
        ->not->toContain('Não implementado — dashboard só em `/gestao`')
        ->not->toContain('**Não há filtro por status**');
});

test('the onboarding known-limits table drops the limits removed by the paridade feature and by the obras/solicitação/navegação increment (RF-31, N-01)', function () {
    expect(onboardingKnownLimitsSection())
        ->not->toContain('Sem filtro por status em Todos os Pedidos')
        ->not->toContain('Sem dashboard próprio para Suprimentos')
        ->not->toContain('Cadastro de obras só por via técnica')
        ->not->toContain('Sem anexos e sem comentários')
        ->toContain('Sem edição do pedido original')
        ->toContain('Sem entrega parcial');
});

test('the onboarding guide describes the filters and the Visão Geral it now has (RF-31)', function () {
    $contents = file_get_contents(base_path('docs/onboarding-albuquerque.md'));

    expect($contents)
        ->toContain('### Visão Geral — o resumo do dia')
        ->not->toContain('Não há filtro por status nesta tela nesta versão');
});

test('the onboarding guide describes the post-increment navigation and cadastros (N-01)', function () {
    $contents = file_get_contents(base_path('docs/onboarding-albuquerque.md'));

    expect($contents)
        ->not->toContain('Cinco colunas')
        ->not->toContain('no menu do topo')
        ->not->toContain('Suprimentos no Kanban e a Gestão no Dashboard')
        ->not->toContain('ninguém se cadastra sozinho')
        ->toContain('Finalizado')
        ->toContain('Preciso para')
        ->toContain('Somente obras ativas')
        ->toContain('Associações');
});
